#!/bin/bash
##author: Zhaoxin Ban
##This is used for downloading data for the five station groups: hmt, nrcs, scan, soilscape and uscrn.
based="/raid4/forecast/pnw_sw_monitor/soil_moisture_obs_update/"
mkdir -p "$based/data/hmt"
mkdir -p "$based/data/nrcs"
mkdir -p "$based/data/scan"
mkdir -p "$based/data/soilscape"  ##now there are no soilscape station has data larger than 5 years.
mkdir -p "$based/data/uscrn"
##Downloading real-time data from hmt.
minp=`echo "scale=6; 0.7/(7305+0.4)"|bc`
#python -c "import datetime as dt; print (dt.datetime.now()-dt.datetime(2018,1,1))"|awk '{print $1}' >> temp.txt
#while read var1 ###download previous seven days data from hmt website 
#do
#        var2=`echo "${var1}-6" |bc`
#        echo $var1
#        echo $var2
#for d in {${var2}..${var1}}
#do
#        for h in {00..23}
#        do
#                curl ftp://ftp1.esrl.noaa.gov/psd2/data/processed/SoilMoisture/czc/2018/${d}/czc18${d}.${h}m > $based/data/hmt/czc18${d}.${h}.txt
#        done
#done
#done<temp.txt
#rm temp.txt
##Downloading real-time data from nrcs.

curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/321:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/321.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/334:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/334.txt
#curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/336:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/336.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/337:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/337.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/340:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/340.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/373:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/373.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/417:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/417.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/443:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/443.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/445:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/445.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/453:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/453.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/454:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/454.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/476:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/476.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/498:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/498.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/503:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/503.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/527:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/527.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/548:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/548.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/549:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/549.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/569:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/569.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/570:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/570.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/573:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/573.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/615:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/615.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/652:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/652.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/698:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/698.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/746:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/746.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/811:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/811.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/849:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/849.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/356:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/356.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/428:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/428.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/462:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/462.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/463:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/463.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/473:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/473.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/508:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/508.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/518:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/518.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/539:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/539.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/540:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/540.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/541:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/541.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/574:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/574.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/575:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/575.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/587:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/587.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/633:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/633.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/697:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/697.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/724:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/724.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/771:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/771.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/778:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/778.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/784:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/784.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/809:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/809.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/834:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/834.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/846:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/846.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/848:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/848.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/1049:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/1049.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/1050:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/1050.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/1051:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/1051.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/1052:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/1052.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/1067:CA:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/1067.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/1006:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/1006.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/1110:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/1110.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/1111:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/1111.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/1112:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/1112.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/1136:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/1136.txt
#curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/1147:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/1147.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/1150:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/1150.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/1155:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/1155.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/1194:NV:SNTL%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-2:qaFlag,SMS:-8:qaFlag,SMS:-20:qaFlag?fitToScreen=false > $based/data/nrcs/1194.txt

##Downloading real-time data from scan.
#curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/750:NV:SCAN%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-4:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN?fitToScreen=false > $based/data/scan/750.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/2116:NV:SCAN%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-4:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN?fitToScreen=false > $based/data/scan/2116.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/2141:NV:SCAN%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-4:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN?fitToScreen=false > $based/data/scan/2141.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/2142:NV:SCAN%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-4:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN?fitToScreen=false > $based/data/scan/2142.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/2144:NV:SCAN%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-4:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN?fitToScreen=false > $based/data/scan/2144.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/2145:NV:SCAN%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-4:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN?fitToScreen=false > $based/data/scan/2145.txt
#curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/2149:CA:SCAN%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-4:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN?fitToScreen=false > $based/data/scan/2149.txt
#curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/2170:NV:SCAN%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-4:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN?fitToScreen=false > $based/data/scan/2170.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/2183:CA:SCAN%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-4:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN?fitToScreen=false > $based/data/scan/2183.txt
#curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/2190:CA:SCAN%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-4:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN?fitToScreen=false > $based/data/scan/2190.txt
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/2192:CA:SCAN%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-4:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN?fitToScreen=false > $based/data/scan/2192.txt 
#curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/2192:CA:SCAN%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-4:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN?fitToScreen=false
curl https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/2187:CA:SCAN%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/SMS:-2:value:hourly%20MEAN,SMS:-4:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN?fitToScreen=false > $based/data/scan/2187.txt
##Downloading real-time data from soilscape.  ##so far, no soilscape stations are needed to be added.
##Downloading real-time data from uscrn.  
date +"%Y" > $based/temp.txt
while read var1
do
	for v in $(eval echo "{2019..$var1}")
	do
		echo "$v" >> $based/temp2.txt
	done
done<$based/temp.txt
	curl ftp://ftp.ncdc.noaa.gov/pub/data/uscrn/products/daily01/2018/CRND0103-2018-CA_Bodega_6_WSW.txt > $based/data/uscrn/Bodega.txt
	curl ftp://ftp.ncdc.noaa.gov/pub/data/uscrn/products/daily01/2018/CRND0103-2018-CA_Redding_12_WNW.txt > $based/data/uscrn/Redding.txt
	curl ftp://ftp.ncdc.noaa.gov/pub/data/uscrn/products/daily01/2018/CRND0103-2018-CA_Santa_Barbara_11_W.txt > $based/data/uscrn/Santa_Barbara.txt
	curl ftp://ftp.ncdc.noaa.gov/pub/data/uscrn/products/daily01/2018/CRND0103-2018-CA_Yosemite_Village_12_W.txt > $based/data/uscrn/Yosemite.txt
	curl ftp://ftp.ncdc.noaa.gov/pub/data/uscrn/products/daily01/2018/CRND0103-2018-NV_Mercury_3_SSW.txt > $based/data/uscrn/Mercury.txt
while read var1
do
	curl ftp://ftp.ncdc.noaa.gov/pub/data/uscrn/products/daily01/${var1}/CRND0103-${var1}-CA_Bodega_6_WSW.txt >> $based/data/uscrn/Bodega.txt
	curl ftp://ftp.ncdc.noaa.gov/pub/data/uscrn/products/daily01/${var1}/CRND0103-${var1}-CA_Redding_12_WNW.txt >> $based/data/uscrn/Redding.txt
	curl ftp://ftp.ncdc.noaa.gov/pub/data/uscrn/products/daily01/${var1}/CRND0103-${var1}-CA_Santa_Barbara_11_W.txt >> $based/data/uscrn/Santa_Barbara.txt
	curl ftp://ftp.ncdc.noaa.gov/pub/data/uscrn/products/daily01/${var1}/CRND0103-${var1}-CA_Yosemite_Village_12_W.txt >> $based/data/uscrn/Yosemite.txt
	curl ftp://ftp.ncdc.noaa.gov/pub/data/uscrn/products/daily01/${var1}/CRND0103-${var1}-NV_Mercury_3_SSW.txt >> $based/data/uscrn/Mercury.txt
done<$based/temp2.txt
rm $based/temp.txt
rm $based/temp2.txt

#date +"%d %m %y" > $based/temp.txt
#while read var1 var2 var3
#do
# var1=`echo "${var1}-1" |bc`
# curl --data "stn=CBVA&smon=$var2&sday=$var1&syea=$var3&emon=$var2&eday=$var1&eyea=$var3&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/cbva.txt
# curl --data "stn=GSPR&smon=$var2&sday=$var1&syea=$var3&emon=$var2&eday=$var1&eyea=$var3&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/gspr.txt
# curl --data "stn=NANV&smon=$var2&sday=$var1&syea=$var3&emon=$var2&eday=$var1&eyea=$var3&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nanv.txt
# curl --data "stn=NCLV&smon=$var2&sday=$var1&syea=$var3&emon=$var2&eday=$var1&eyea=$var3&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nclv.txt
# curl --data "stn=NCVA&smon=$var2&sday=$var1&syea=$var3&emon=$var2&eday=$var1&eyea=$var3&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/ncva.txt
# curl --data "stn=NMAS&smon=$var2&sday=$var1&syea=$var3&emon=$var2&eday=$var1&eyea=$var3&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nmas.txt
# curl --data "stn=NNSV&smon=$var2&sday=$var1&syea=$var3&emon=$var2&eday=$var1&eyea=$var3&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nnsv.txt
# curl --data "stn=NPVA&smon=$var2&sday=$var1&syea=$var3&emon=$var2&eday=$var1&eyea=$var3&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/npva.txt
# curl --data "stn=NPWL&smon=$var2&sday=$var1&syea=$var3&emon=$var2&eday=$var1&eyea=$var3&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/npwl.txt
 #curl --data "stn=NREE&smon=$var2&sday=$var1&syea=$var3&emon=$var2&eday=$var1&eyea=$var3&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nree.txt
 #curl --data "stn=NSMV&smon=$var2&sday=$var1&syea=$var3&emon=$var2&eday=$var1&eyea=$var3&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nsmv.txt
 #curl --data "stn=NSNA&smon=$var2&sday=$var1&syea=$var3&emon=$var2&eday=$var1&eyea=$var3&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nsna.txt
 #curl --data "stn=NSPA&smon=$var2&sday=$var1&syea=$var3&emon=$var2&eday=$var1&eyea=$var3&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nspa.txt
 #curl --data "stn=NSSV&smon=$var2&sday=$var1&syea=$var3&emon=$var2&eday=$var1&eyea=$var3&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nssv.txt
 #curl --data "stn=NSTV&smon=$var2&sday=$var1&syea=$var3&emon=$var2&eday=$var1&eyea=$var3&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nstv.txt
 #curl --data "stn=NSWM&smon=$var2&sday=$var1&syea=$var3&emon=$var2&eday=$var1&eyea=$var3&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nswm.txt
 #curl --data "stn=WNCC&smon=$var2&sday=$var1&syea=$var3&emon=$var2&eday=$var1&eyea=$var3&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/wncc.txt
#done<temp.txt
#rm temp.txt
###This is to download data from VIC model
#while read var1
#do
#        sshpass -p "geog@123" scp -r mxiao@128.97.63.197:/raid4/forecast/pnw_sw_monitor/data/nev/results/curr_spinup/vic/daily/asc/$var1 data/vic/new$var1
#        sshpass -p "geog@123" scp -r mxiao@128.97.63.197:/raid4/forecast/pnw_sw_monitor/data/cali1/results/curr_spinup/vic/daily/asc/$var1 data/vic/new$var1
#        sshpass -p "geog@123" scp -r mxiao@128.97.63.197:/raid4/forecast/pnw_sw_monitor/data/cali2/results/curr_spinup/vic/daily/asc/$var1 data/vic/new$var1
#        sshpass -p "geog@123" scp -r mxiao@128.97.63.197:/raid4/forecast/pnw_sw_monitor/data/gb/results/curr_spinup/vic/daily/asc/$var1 data/vic/new$var1
#        sshpass -p "geog@123" scp -r mxiao@128.97.63.197:/raid4/forecast/pnw_sw_monitor/data/colo1/results/curr_spinup/vic/daily/asc/$var1 data/vic/new$var1
#        sshpass -p "geog@123" scp -r mxiao@128.97.63.197:/raid4/forecast/pnw_sw_monitor/data/colo2/results/curr_spinup/vic/daily/asc/$var1 data/vic/new$var1
#        sshpass -p "geog@123" scp -r mxiao@128.97.63.197:/raid4/forecast/pnw_sw_monitor/data/pnw1/results/curr_spinup/vic/daily/asc/$var1 data/vic/new$var1
#        mv data/vic/new$var1 data/vic/$var1
#done<scpname


