#!/bin/bash
##author: Zhaoxin Ban
##This is used for downloading data for the five station groups: hmt, nrcs, scan, soilscape and uscrn.
based="/raid4/forecast/pnw_sw_monitor/soil_moisture_obs_update/"
mkdir -p "$based/data/hmt"
mkdir -p "$based/data/nrcs"
mkdir -p "$based/data/scan"
mkdir -p "$based/data/soilscape"  ##now there are no soilscape station has data larger than 5 years.
mkdir -p "$based/data/uscrn"
date +"%d %m %y" > $based/data/wrcc/today
paste $based/data/wrcc/last6 $based/data/wrcc/today > $based/data/wrcc/temp
while read var1 var2 var3 var4 var5 var6
do
# var1=`echo "${var1}-1" |bc`
# curl --data "stn=CBVA&smon=$var2&sday=$var1&syea=$var3&emon=$var5&eday=$var4&eyea=$var6&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/cbva.txt
# curl --data "stn=GSPR&smon=$var2&sday=$var1&syea=$var3&emon=$var5&eday=$var4&eyea=$var6&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/gspr.txt
# curl --data "stn=NANV&smon=$var2&sday=$var1&syea=$var3&emon=$var5&eday=$var4&eyea=$var6&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nanv.txt
# curl --data "stn=NCLV&smon=$var2&sday=$var1&syea=$var3&emon=$var5&eday=$var4&eyea=$var6&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nclv.txt
# curl --data "stn=NCVA&smon=$var2&sday=$var1&syea=$var3&emon=$var5&eday=$var4&eyea=$var6&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/ncva.txt
# curl --data "stn=NMAS&smon=$var2&sday=$var1&syea=$var3&emon=$var5&eday=$var4&eyea=$var6&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nmas.txt
# curl --data "stn=NNSV&smon=$var2&sday=$var1&syea=$var3&emon=$var5&eday=$var4&eyea=$var6&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nnsv.txt
# curl --data "stn=NPVA&smon=$var2&sday=$var1&syea=$var3&emon=$var5&eday=$var4&eyea=$var6&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/npva.txt
# curl --data "stn=NPWL&smon=$var2&sday=$var1&syea=$var3&emon=$var5&eday=$var4&eyea=$var6&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/npwl.txt
# curl --data "stn=NREE&smon=$var2&sday=$var1&syea=$var3&emon=$var5&eday=$var4&eyea=$var6&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nree.txt
# curl --data "stn=NSMV&smon=$var2&sday=$var1&syea=$var3&emon=$var5&eday=$var4&eyea=$var6&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nsmv.txt
# curl --data "stn=NSNA&smon=$var2&sday=$var1&syea=$var3&emon=$var5&eday=$var4&eyea=$var6&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nsna.txt
# curl --data "stn=NSPA&smon=$var2&sday=$var1&syea=$var3&emon=$var5&eday=$var4&eyea=$var6&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nspa.txt
# curl --data "stn=NSSV&smon=$var2&sday=$var1&syea=$var3&emon=$var5&eday=$var4&eyea=$var6&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nssv.txt
# curl --data "stn=NSTV&smon=$var2&sday=$var1&syea=$var3&emon=$var5&eday=$var4&eyea=$var6&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nstv.txt
# curl --data "stn=NSWM&smon=$var2&sday=$var1&syea=$var3&emon=$var5&eday=$var4&eyea=$var6&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/nswm.txt
# curl --data "stn=WNCC&smon=$var2&sday=$var1&syea=$var3&emon=$var5&eday=$var4&eyea=$var6&qM04=ON&qM08=ON&qM20=ON&unit=M&Ofor=A&Datareq=A&qc=Y&miss=08&pbs=N&WsMon=01&WsDay=01&WeMon=12&WeDay=31&Submit%%20Info=Submit%%20Info&.cgifields=Datareq,qc,qM04,qRH,qPE,qAV4,qGD4,qFT,qM20,qAT,qCDD,qWD,qM08,qGD5,qBP,qAE,qPR,qA20,unit,qBasic,Ofor,qRS,qAV8,qBT,obs,qST,qHDD" "https://wrcc.dri.edu/cgi-bin/wea_dysimts2.pl" > $based/data/wrcc/wncc.txt
done<$based/data/wrcc/temp
mv $based/data/wrcc/last5 $based/data/wrcc/last6
mv $based/data/wrcc/last4 $based/data/wrcc/last5
mv $based/data/wrcc/last3 $based/data/wrcc/last4
mv $based/data/wrcc/last2 $based/data/wrcc/last3
mv $based/data/wrcc/yesterday $based/data/wrcc/last2
mv $based/data/wrcc/today $based/data/wrcc/yesterday
